[theme]
primaryColor = "#1abc9c"
backgroundColor = "#ecf0f1"
secondaryBackgroundColor = "#bdc3c7"
textColor = "#2c3e50"
font = "sans serif"

[server]
port = 8502
enableStaticServing = true

[browser]
gatherUsageStats = false
